core/urls.py
from django.urls import include, path

from . import views

app_name = 'core'

urlpatterns = [
    path('employee/', include([
        path('list/', views.EmployeeList.as_view(), name='employee-list'),
        path('create/', views.EmployeeCreate.as_view(), name='employee-create'),
        path('<int:pk>/edit', views.EmployeeUpdate.as_view(), name='employee-update'),
        path('<int:pk>/delete', views.EmployeeDelete.as_view(), name='employee-delete'),
    ])),

    path('sibling/<int:employee_id>/', include([
        path('', views.FamilyMemberList.as_view(), name='sibling-list'),
        path('create/', views.FamilyMemberCreate.as_view(), name='sibling-create'),
        path('<int:pk>/update/', views.FamilyMemberUpdate.as_view(), name='sibling-update'),
        path('<int:pk>/delete/', views.FamilyMemberDelete.as_view(), name='sibling-delete'),
    ])),

    path('<int:pk>/salary-details/view', views.SalaryDetails.as_view(), name='salary-detail-view'),
    path('<int:employee_id>/salary-details/create', views.SalaryDetailCreate.as_view(), name='salary-detail-create'),

    path('<int:salary_details_id>/deduction/create', views.DeductionCreate.as_view(), name='deduction-create'),
    path('<int:salary_details_id>/earning/create', views.EarningCreate.as_view(), name='earning-create'),
]

mashreqarabia_task/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models

from .utils import calculate_age, calculate_default_deductions


class Country(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Countries'


class Job(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Employee(models.Model):
    POSITION_CHOICES = (
        ('E', 'Employee'),
        ('M', 'Manager'),
        ('C', 'CEO')
    )

    MARITAL_STATUS_CHOICES = (
        ('S', 'Single'),
        ('M', 'Married')
    )

    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other')
    )

    first_name = models.CharField(max_length=80)
    middle_name = models.CharField(max_length=80)
    last_name = models.CharField(max_length=80)
    job = models.ForeignKey(Job, null=True, blank=True, on_delete=models.SET_NULL)
    position = models.CharField(max_length=1, choices=POSITION_CHOICES)
    national_id = models.CharField(unique=True, max_length=settings.NATIONAL_ID_LENGTH,
                                   validators=[
                                       RegexValidator(
                                           regex=settings.NATIONAL_ID_REGEX,
                                           message='National id must be {} digits'.format(settings.NATIONAL_ID_LENGTH),
                                           code='invalid_national_id'
                                       )
                                   ])
    date_of_birth = models.DateField()
    place_of_birth = models.CharField(max_length=255)
    country = models.ForeignKey(Country, on_delete=models.PROTECT)
    nationality = models.CharField(max_length=100)
    marital_status = models.CharField(max_length=1, choices=MARITAL_STATUS_CHOICES)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)

    terminated = models.BooleanField(default=False, editable=False)

    @property
    def full_name(self):
        return '{} {} {}'.format(self.first_name,
                                 self.middle_name,
                                 self.last_name)

    @property
    def age(self):
        return calculate_age(self.date_of_birth)

    @property
    def is_married(self):
        return self.marital_status == "M"

    def __str__(self):
        return self.full_name


class FamilyMember(models.Model):
    RELATIONS_CHOICES = (
        ('C', 'Child'),
        ('W', 'Wife'),
        ('H', 'Husband')
    )

    relation_type = models.CharField(max_length=1, choices=RELATIONS_CHOICES)
    name = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)

    @property
    def age(self):
        return calculate_age(self.date_of_birth)

    def __str__(self):
        return self.name


class SalaryDetail(models.Model):
    amount = models.DecimalField(max_digits=7, decimal_places=2)
    employee = models.OneToOneField(Employee, on_delete=models.CASCADE)

    @property
    def main_salary(self):
        return self.amount

    @staticmethod
    def _aggregation_value(aggregation):
        value = aggregation.get('amount__sum')
        return value if value else 0

    @property
    def total_earnings(self):
        aggregation = self.earnings.aggregate(models.Sum('amount'))
        return self._aggregation_value(aggregation)

    @property
    def total_deductions(self):
        deductions = self.deductions

        if not deductions.exists():
            return calculate_default_deductions(self.employee.position, self.main_salary)

        aggregation = self.deductions.aggregate(models.Sum('amount'))
        return self._aggregation_value(aggregation)

    @property
    def total_salary(self):
        return self.main_salary + self.total_earnings - self.total_deductions

    def __str__(self):
        return 'Salary details for {}'.format(self.employee.full_name)


class Earning(models.Model):
    amount = models.DecimalField(max_digits=7, decimal_places=2)
    reason = models.CharField(max_length=255, blank=True)
    salary_details = models.ForeignKey(SalaryDetail, on_delete=models.CASCADE, related_name='earnings')

    def __str__(self):
        return '{} for {}'.format(self.amount, self.reason)


class Deduction(models.Model):
    amount = models.DecimalField(max_digits=7, decimal_places=2)
    reason = models.CharField(max_length=255, blank=True)
    salary_details = models.ForeignKey(SalaryDetail, on_delete=models.CASCADE, related_name='deductions')

    def __str__(self):
        return '- {} for {}'.format(self.amount, self.reason)

core/forms.py
import datetime

from django import forms
from django.conf import settings

from .models import Employee, FamilyMember, SalaryDetail, Deduction, Earning
from .utils import valid_salary

VALID_YEARS = tuple(year for year in range(settings.MIN_BORN_YEAR, datetime.datetime.now().year + 1))


class EmployeeForm(forms.ModelForm):

    def clean_national_id(self):
        if self.instance.national_id:
            return self.instance.national_id
        return self.cleaned_data['national_id']

    class Meta:
        model = Employee
        fields = ['first_name', 'middle_name', 'last_name', 'job', 'position', 'national_id', 'date_of_birth',
                  'place_of_birth', 'country', 'nationality', 'marital_status', 'gender']

        widgets = {
            'date_of_birth': forms.SelectDateWidget(years=VALID_YEARS)
        }


class FamilyMemberForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.employee = kwargs['initial'].get('employee')
        super(FamilyMemberForm, self).__init__(*args, **kwargs)

    def clean_employee(self):
        if self.employee:
            return self.employee
        return self.cleaned_data['employee']

    class Meta:
        model = FamilyMember
        fields = ['relation_type', 'name', 'date_of_birth', 'employee']

        widgets = {
            'date_of_birth': forms.SelectDateWidget(years=VALID_YEARS),
            'employee': forms.TextInput(attrs={
                'readonly': 'true'
            })
        }


class SalaryDetailForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.employee = kwargs['initial'].get('employee')
        super(SalaryDetailForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()

        position = self.employee.position
        amount = cleaned_data.get("amount")

        if position and amount:
            if not valid_salary(position, amount):
                raise forms.ValidationError('Invalid salary range.')

        return cleaned_data

    class Meta:
        model = SalaryDetail
        fields = ['amount', 'employee']

        widgets = {
            'employee': forms.TextInput(attrs={
                'readonly': 'true'
            })
        }


class DeductionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.salary_details = kwargs['initial'].get('salary_details')
        super(DeductionForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Deduction
        fields = ['amount', 'reason', 'salary_details']

        widgets = {
            'salary_details': forms.TextInput(attrs={
                'readonly': 'true'
            })
        }


class EarningForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.salary_details = kwargs['initial'].get('salary_details')
        super(EarningForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Earning
        fields = ['amount', 'reason', 'salary_details']

        widgets = {
            'salary_details': forms.TextInput(attrs={
                'readonly': 'true'
            })
        }

core/views.py
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic

from .forms import EmployeeForm, FamilyMemberForm, SalaryDetailForm, DeductionForm, EarningForm
from .models import Employee, FamilyMember, SalaryDetail


class EmployeeTerminateMixin:
    def dispatch(self, request, *args, **kwargs):
        if self.get_employee().terminated:
            raise Http404('Terminated employee.')

        return super().dispatch(request, *args, **kwargs)

    def get_employee(self):
        return self.get_object()


class EmployeeSiblingMixin(EmployeeTerminateMixin):
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['employee'] = self.get_employee()
        return context

    def get_success_url(self):
        return reverse('core:sibling-list', kwargs={'employee_id': self.get_employee_id()})

    def get_employee(self):
        return get_object_or_404(Employee, pk=self.get_employee_id())

    def get_employee_id(self):
        return self.kwargs.get('employee_id')


class SalaryDetailMixin(EmployeeTerminateMixin):
    def get_initial(self):
        initial = super().get_initial()
        initial['salary_details'] = self.get_salary_detail()
        return initial

    def get_success_url(self):
        return reverse('core:salary-detail-view', kwargs={
            'pk': self.get_salary_detail_id()
        })

    def get_salary_detail(self):
        return get_object_or_404(SalaryDetail, pk=self.get_salary_detail_id())

    def get_salary_detail_id(self):
        return self.kwargs.get('salary_details_id')

    def get_employee(self):
        return self.get_salary_detail().employee


class EmployeeList(generic.ListView):
    model = Employee
    context_object_name = 'employees'
    template_name = 'core/employee_list.html'


class EmployeeCreate(generic.CreateView):
    form_class = EmployeeForm
    template_name = 'core/employee_create.html'
    success_url = reverse_lazy('core:employee-list')


class EmployeeUpdate(EmployeeTerminateMixin, generic.UpdateView):
    model = Employee
    form_class = EmployeeForm
    template_name = 'core/employee_update.html'
    success_url = reverse_lazy('core:employee-list')


class EmployeeDelete(EmployeeTerminateMixin, generic.DeleteView):
    model = Employee
    template_name = 'core/employee_delete.html'
    success_url = reverse_lazy('core:employee-list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()

        if not self.object.job:
            self.object.delete()
        else:
            self.object.terminated = True
            self.object.save()

        return HttpResponseRedirect(success_url)


class FamilyMemberList(EmployeeSiblingMixin, generic.ListView):
    template_name = 'core/sibling_list.html'
    context_object_name = 'members'

    def get_queryset(self):
        employee_id = self.kwargs.get('employee_id')
        employee = self.get_employee()

        if not employee.is_married:
            raise Http404('Not a married employee')

        return FamilyMember.objects.filter(employee_id=employee_id)


class FamilyMemberCreate(EmployeeSiblingMixin, generic.CreateView):
    form_class = FamilyMemberForm
    template_name = 'core/sibling_create.html'

    def get_initial(self):
        initial = super(FamilyMemberCreate, self).get_initial()
        initial['employee'] = self.get_employee()
        return initial


class FamilyMemberUpdate(EmployeeSiblingMixin, generic.UpdateView):
    model = FamilyMember
    form_class = FamilyMemberForm
    template_name = 'core/sibling_update.html'


class FamilyMemberDelete(EmployeeSiblingMixin, generic.DeleteView):
    model = FamilyMember
    template_name = 'core/sibling_delete.html'


class SalaryDetails(generic.DetailView):
    model = SalaryDetail
    context_object_name = 'salary_details'
    template_name = 'core/salary_details.html'


class SalaryDetailCreate(EmployeeSiblingMixin, generic.CreateView):
    form_class = SalaryDetailForm
    template_name = 'core/salary_detail_create.html'

    def get_initial(self):
        initial = super(SalaryDetailCreate, self).get_initial()
        initial['employee'] = self.get_employee()
        return initial

    def get_success_url(self):
        return reverse('core:salary-detail-view', kwargs={'pk': self.object.id})


class DeductionCreate(SalaryDetailMixin, generic.CreateView):
    form_class = DeductionForm
    template_name = 'core/deduction_create.html'


class EarningCreate(SalaryDetailMixin, generic.CreateView):
    form_class = EarningForm
    template_name = 'core/earning_create.html'

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
{% block content %}
{% endblock content %}
</body>
</html>

core/templates/core/deduction_create.html
{% extends "core/base.html" %}

{% block title %}Create Deduction{% endblock %}

{% block content %}
    <div class="deduction-form">
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
{% endblock %}

core/templates/core/earning_create.html
{% extends "core/base.html" %}

{% block title %}Create Earning{% endblock %}

{% block content %}
    <div class="earning-form">
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
{% endblock %}

core/templates/core/employee_create.html
{% extends "core/base.html" %}

{% block title %}Create Employee{% endblock %}

{% block content %}
    <div class="employee-form">
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <button>Add</button>
        </form>
    </div>
{% endblock %}

core/templates/core/employee_delete.html
{% extends "core/base.html" %}

{% block title %}Delete Employee{% endblock %}

{% block content %}
    <div>
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <button>Confirm</button>
        </form>
    </div>
{% endblock %}

core/templates/core/employee_list.html
{% extends "core/base.html" %}

{% block title %}Employees list{% endblock %}

{% block content %}
    <div class="employee-create">
        <a href="{% url 'core:employee-create' %}">New Employee</a>
    </div>
    <div class="employee-list">
        <ul>
            {% for employee in employees %}
                <li class="employee-details">
                    <p>{{ employee.full_name }}</p>
                    {% if not employee.terminated %}
                        {% if employee.salarydetail %}
                            <a href="{% url 'core:salary-detail-view' employee.salarydetail.id %}">Salary Details</a>
                        {% else %}
                            <a href="{% url 'core:salary-detail-create' employee.id %}">New Salary Details</a>
                        {% endif %}

                        <a href="{% url 'core:employee-update' employee.id %}">Update</a>
                        <a href="{% url 'core:employee-delete' employee.id %}">Delete</a>
                        {% if employee.is_married %}
                            <a href="{% url 'core:sibling-list' employee.id %}">Siblings</a>
                        {% endif %}
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

core/templates/core/employee_update.html
{% extends "core/base.html" %}

{% block title %}Update Employee{% endblock %}

{% block content %}
    <div class="employee-form">
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <button>Update</button>
        </form>
    </div>
{% endblock %}

core/templates/core/salary_detail_create.html
{% extends "core/base.html" %}

{% block title %}Create Salary{% endblock %}

{% block content %}
    <div class="salary-form">
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <button>Add</button>
        </form>
    </div>
{% endblock %}

core/templates/core/salary_details.html
{% extends "core/base.html" %}

{% block title %}Salary Details{% endblock %}

{% block content %}
    <div class="salary-details">
        <p>Name: {{ salary_details.employee.full_name }}</p>
        <p>Main Salary: {{ salary_details.main_salary }}</p>
        <p>Deductions: {{ salary_details.total_deductions }}</p>
        <p>Earnings: {{ salary_details.total_earnings }}</p>
        <p>Total Salary: {{ salary_details.total_salary }}</p>

        <a href="{% url 'core:deduction-create' salary_details.id %}">New Deduction</a>
        <a href="{% url 'core:earning-create' salary_details.id %}">New Earning</a>
    </div>
{% endblock %}

core/templates/core/sibling_create.html
{% extends "core/base.html" %}

{% block title %}Create Sibling{% endblock %}

{% block content %}
    <div class="sibling-form">
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <button>Add</button>
        </form>
    </div>
{% endblock %}

core/templates/core/sibling_delete.html
{% extends "core/base.html" %}

{% block title %}Delete Sibling{% endblock %}

{% block content %}
    <div>
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <button>Confirm</button>
        </form>
    </div>
{% endblock %}

core/templates/core/sibling_list.html
{% extends "core/base.html" %}

{% block title %}Siblings list{% endblock %}

{% block content %}
    <div class="sibling-create">
        <a href="{% url 'core:sibling-create' employee.id %}">New Sibling</a>
    </div>
    <div class="sibling-list">
        <ul>
            {% for member in members %}
                <li class="sibling-details">
                    <p>{{ member.get_relation_type_display }}</p>
                    <p>{{ member.name }}</p>
                    <a href="{% url 'core:sibling-update' employee.id member.id %}">Update</a>
                    <a href="{% url 'core:sibling-delete' employee.id member.id %}">Delete</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

core/templates/core/sibling_update.html
{% extends "core/base.html" %}

{% block title %}Update Sibling{% endblock %}

{% block content %}
    <div class="sibling-form">
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <button>Update</button>
        </form>
    </div>
{% endblock %}